#!/usr/bin/env bash
# i hate network, really. Hell yes

sudo apt update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo echo 'Hello World' > /var/www/html/index.html
sudo service nginx restart
