#!/usr/bin/env bash
# i hate network, really.

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee file /var/www/html/index.nginx-debian.html
sudo service nginx restart
