#!/usr/bin/env bash
# i hate network, really.

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sudo service nginx restart
