#!/usr/bin/env bash
# i hate network, really.

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sed -i "/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sed -i "/location/a \                error_page 404 /code_404.html;\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/code_404.html
sudo service nginx restart
