#!/usr/bin/env bash
# LB
# web-01 web-02
apt update
apt install -y haproxy=1.5.\*

printf %s "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
    balance roundrobin
    server 3338-web-01 34.74.161.43:80 check
    server 3338-web-02 35.185.60.222:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
