#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times

while [[ $x -le 10 ]]
do
    if [[ $x -eq 9 ]]
    then
	echo "Hi"
    else
	echo "Best School"
    fi
    x=$(( x + 1 ))
done
