#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:

while [[ $x -le 9 ]]
do
    if [[ $x -eq 3 ]]
    then
	echo "bad luck"
    elif [[ $x -eq 7 ]]
    then
    	echo "good luck"
    else
	echo "Best School"
    fi
    x=$(( x + 1 ))
done
