#!/usr/bin/env bash
# Write a Bash script that displays:

if [[ -e $File ]]
then
    echo "school file exists"
    if [[ -s $File ]]
    then
        echo "school file is not empty"
    elif [[ -f $File ]]
    then
        echo "school is a regular file"
    else
        echo "school file is empty"
    fi
else
echo "school file does not exists"
fi
