#!/usr/bin/bash
#install ufw, 
# Configure ufw in 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

# update
sudo apt-get update
# install ufw
sudo apt install ufw
# allow ufw configuration
sudo ufw default deny incoming
# add connection por 22: SSH
sudo ufw allow 22
# add connection por 443: HTTPS
sudo ufw allow 443
# add connection por 80: HTTP
sudo ufw allow 80
# restart firewall and allow
sudo ufw enable
